services:
  mtproto-proxy:
    #image: telegrammessenger/proxy:latest
    build:
      context: .
      args:
        MTPROTO_REPO_URL: ${MTPROTO_REPO_URL}
    container_name: mtproto-proxy
    volumes:
      - ./volumes/config:/data
    restart: unless-stopped
    ports:
      - ${PORT}:8889/udp
      - ${PORT}:8889/tcp
    environment:
      - SECRET
      - WORKERS
      - MTPROTO_REPO_URL
      - IP
      - PORT
